user:
  outputs:
    default:
      keyfile_json:
        auth_provider_x509_cert_url: https://www.googleapis.com/oauth2/v1/certs
        auth_uri: https://accounts.google.com/o/oauth2/auth
        client_email: aziz-zmcmp@dt-eng-zmcmp.iam.gserviceaccount.com
        client_id: '105054691302446942890'
        client_x509_cert_url: https://www.googleapis.com/robot/v1/metadata/x509/aziz-zmcmp%40dt-eng-zmcmp.iam.gserviceaccount.com
        private_key: '-----BEGIN PRIVATE KEY-----

          MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDFL8S3NvX8e0cA

          zbZGdxb3BTi2KmMHRbkTQJdYYzJ7xPFo4P49g4BA5OJzlemvTe1e1zpKnRV7L6ek

          l73oT5slxbY6YL0esOkE/fLGilCn0vfe9vE9ZwlhJoxa8wJRqes3QMpoYDjIn6t+

          l286DfRuRSSYZ/XPt8Bv5Bmu1Ej2FmC7+QMJ4uEzB858HlyaefgEaxUP0q+ShDSs

          63oQ+nqPx+t+8k0KAVyyjVVCrueUqtw5HlTWRK04vSDvOLHG0qtStK7Y4Qf7S7tl

          qWM7V3apWwuEhArLDjCMSkB7Bjoc6mtpK0qlI4TX6etpfuseiqiBsaq2GH4Gx3Ee

          X2bhZQ3/AgMBAAECggEABr/SOLMyfqhGXEpH3IGXBHCy6dYcxzlYhfnGZ5Z9oKuz

          cUBb2dJc2w76iucTgi/L2cMw+GM7Qpj1YNAQ0zLMv+FuK1fEVJiZlG72Y47roJ+7

          L3AkZOwLiVe+1h4bP9BUTL/a+orQmfPDjigaY1JQjrWvJ8hNkZ6O56vwqE571z09

          c0HCtcG1KrDKNSHdple4rYfur6X4DGq1qhjU1Q/fdgvrtp6etfWmJ88S9wj6crFH

          iaw6TlvaYLHf2x6x+9A4dMVkMkJ93/YbCJ96EZi4BTqGtVIOXbbmNlvE6bb5izKU

          KoOfYoGkP3i1aZaG05Wa4ugD0AqG6w6+kcF7JAE0AQKBgQDrIVofMPolmI9Bam3N

          rq4WMHFSQpALJF8RGEeafjPnZa/8S7FSk2VEN8Jhc0SDeMjYs9ZtlsrWffLWPxQo

          u6Bc3uDiTt/nBFO06NLqOcXAsKAaW0qc+ZSZdzyqj6MMcdz8xsznsTK1o7Mh1M9P

          uWr4dfH5EFWiOqQYRJI78b6xXwKBgQDWsEHQutMJEfCBb/4G3PDg3QkqYbpHCKwF

          0RGNpTqOG0hN3EEZtmLWq385OuFGSr/6mghFWuSS1SWG7DMbv1mgDRazkC4IN4TU

          mfMEBaIkfncdXehM+iQNWjapYRVivQYzcItFZzlxOPGS567UToYdulhO20TNpeCD

          hW+q253HYQKBgQCV0/XahFoR1OoMNCZt905lQ08irNmez/loKkGOV7b5T5nZud3v

          kY7o7mMFt+7DnBbXx5ju0jTEgxNXpHBTGGQyaa+BZeNVETPJxsaHjHLPu3z57oxY

          BM3FEO7ufILYbkH0LTXqucZnaj2+ZB4KXkuksXuUSu1WZ+misSdB3WS3HwKBgGmr

          LWnQWsjvFIKRHeZA3yq+gKFkoqwN36WpRsuCFPUXBpqUG1LNi45/sMn5aiIP7rgp

          EoMYfsKquKLVJT62CyYU6ySMhauzr+R4tb04DJuLx5MjwpAI2q/bxGXQDBeiVCgD

          b/lEGmjZD0YwVMPYtnhxXL/Leu0BhSUXC2R8XgdhAoGAV1vFhlDnXwYdB6y722l+

          g1lLkcCX7S6fENQVgLQbzxFpF3McVRFOFmMGdem5zTof5mm31Rocgg6J6mWX64b6

          quRre54PklqELhflSztNdyS2yiQBl58Wn3kZT4LPhLjfzhSLmCsJ1hzW4rqQJQQ1

          QqJXgq3wvX9kOnpLbUPkIzw=

          -----END PRIVATE KEY-----

          '
        private_key_id: 44b2b0e39a2ec82f46e14e9de133b7cd15d90f23
        project_id: dt-eng-zmcmp
        token_uri: https://oauth2.googleapis.com/token
        type: service_account
      method: service-account-json
      project: dt-eng-zmcmp
      schema: zoomcamp
      scopes:
      - https://www.googleapis.com/auth/bigquery
      - https://www.googleapis.com/auth/cloud-platform
      - https://www.googleapis.com/auth/drive
      - https://www.googleapis.com/auth/userinfo.email
      target_name: default
      threads: 4
      type: bigquery
  target: default
